## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.7
  - 1.0
  - nightly
notifications:
  email: false
git:
  depth: 99999999

# uncomment the following lines to allow failures on nightly julia
# (tests will run but not make your overall status red)
matrix:
 allow_failures:
 - julia: nightly

script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'using Pkg; Pkg.clone(pwd()); Pkg.build("HurdleDMR"); Pkg.test("HurdleDMR"; coverage=true)'

after_success:
  - julia -e 'Pkg.add("Documenter")'
  - julia -e 'using Pkg; cd(Pkg.dir("HurdleDMR")); include(joinpath("docs", "make.jl"))'
  - julia -e 'using Pkg; cd(Pkg.dir("HurdleDMR")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # - julia -e 'cd(Pkg.dir("HurdleDMR")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
